# Project information
site_name: "packageR Docs"
site_description: "Documentation of the packageR."
copyright: "Copyright &copy; 2024, Versioneer"

# Configuration
dev_addr: "127.0.0.1:5000"
site_dir: "build/html"
docs_dir: "src"
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  logo: assets/img/logo.png
  favicon: assets/img/favicon.ico
  palette:
    - scheme: default
      primary: white

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: [".", "src"]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true

# Plugins
plugins:
  - macros:
      render_by_default: false
  - search:
      lang: en
  - swagger-ui-tag
  - tags

# Page tree
nav:
  - Home:
      - index.md
      - packageR:
        - intro/features.md
        - intro/components.md
  - Workflows:
      - workflows/index.md
      - Personas:
          - workflows/data-curation.md
          - workflows/data-governance.md
          #- workflows/data-use.md
  - Components:
      - components/index.md
      - components/ui.md
      - components/api.md
  #- Tutorials:
  #    - tutorials/index.md
  #    - tutorials/e2e.md

# Footer links
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/versioneer-tech/package-r"
    - icon: fontawesome/solid/copyright
      link: "https://versioneer.at"
